import express from'express';import{createServer as createViteServer}from'vite';import path from'path';import{fileURLToPath}from'url';import dotenv from'dotenv';import{GoogleGenAI}from'@google/genai';dotenv.config();const __filename=fileURLToPath(import.meta.url),__dirname=path.dirname(__filename),isProduction=process.env.NODE_ENV==='production',PORT=Number(process.env.PORT||3000),apiKey=process.env.GEMINI_API_KEY,model=process.env.GEMINI_MODEL||'gemini-2.5-flash',ai=apiKey?new GoogleGenAI({apiKey}):null;
const OWNER_EMAIL='farinasmumtaj6399@gmail.com';
async function notifyOwner(subject:string,html:string){const key=process.env.RESEND_API_KEY,from=process.env.RESEND_FROM_EMAIL;if(!key||!from)return;try{await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+key,'Content-Type':'application/json'},body:JSON.stringify({from,to:[OWNER_EMAIL],subject,html})})}catch(error){console.error('FARINAS AI email notification failed:',error)}}
const SYSTEM_INSTRUCTION=`You are FARINAS AI, the official portfolio assistant for FARINAS MUMTAJ H. Answer only from the verified portfolio context below. Never invent features, metrics, awards, clients, links, deployments, certifications or technical capabilities. If the requested fact is not provided, say: "That information is not currently provided in Farinas's portfolio." Keep answers concise, natural and professional.
IDENTITY: FARINAS MUMTAJ H; AI CREATIVE DESIGNER; ECE student at Sir Isaac Newton College of Engineering and Technology, Pappakovil–Nagapattinam; VIBE CODER; interests include UI/UX Design, AI, Prompt Engineering, Creative Technology, ECE, photography and video editing; President of DENSHI Innovation Club under the Skill Development Cell.
PROJECTS: 01 OBSTACLE AVOIDANCE ROBOT — Arduino-based robot using an ultrasonic sensor to detect obstacles and control movement to avoid collisions; Arduino, Ultrasonic Sensor, Motor Driver, Motors, Embedded Logic; Hardware Project / Prototype. 02 FINANCE CHATBOT — AI-powered conversational finance project exploring interaction with financial information through a simple chat-based interface; AI, Prompt Engineering, Conversational UI, Financial Information. 03 AI RESEARCH AGENT — AI-assisted research project exploring how AI can organize research tasks, process information and structure findings; AI Agents, Prompt Engineering, Research Workflow, Information Organization. 04 AI-BASED SMART ATTENDANCE SYSTEM — QR-based attendance concept with a digital dashboard; React, TypeScript, Tailwind CSS, Local Storage, QR Code, Dashboard Analytics. 05 ECOCART — digital shopping concept exploring a sustainable and user-friendly shopping experience; UI/UX, Product Design, Sustainability, Digital Experience. 06 CAMPUSCONNECT — student-focused digital platform concept for useful campus information and services; UI/UX, Information Architecture, Student Experience, Digital Product Design. 07 BANKWISE — digital finance/banking interface concept focused on presenting financial information simply; UI/UX, Information Design, FinTech. 08 AI INNOVATE SYMPOSIUM WEBSITE — AI-assisted web design project created using Google AI Studio and prompt engineering workflows; Google AI Studio, HTML, CSS, JavaScript, Prompt Engineering, UI/UX. 09 TRUEWEATHER — weather-focused web project created through AI-assisted development and interface experimentation; discuss only features actually implemented.
TOOLS: Google AI Studio, Figma, Canva, ChatGPT, HTML, CSS, JavaScript, React, TypeScript, C, CapCut, Adobe, Lightroom, Google Sites, Wix, SketchUp, Prompt Engineering. CONTACT: farinasmumtaj6399@gmail.com`;
function history(input:unknown){if(!Array.isArray(input))return[];return input.slice(-8).flatMap((x:any)=>{const role=x?.role==='model'||x?.sender==='bot'?'model':x?.role==='user'||x?.sender==='user'?'user':null;const text=typeof x?.content==='string'?x.content:typeof x?.text==='string'?x.text:'';return role&&text?[{role,parts:[{text}]}]:[]})}
async function start(){const app=express();app.disable('x-powered-by');app.use(express.json({limit:'1mb'}));app.get('/api/health',(_,res)=>res.json({ok:true,aiConfigured:Boolean(ai),model}));app.post('/api/chat',async(req,res)=>{try{const message=typeof req.body?.message==='string'?req.body.message.trim():'';if(!message)return res.status(400).json({error:'Message text is required.'});if(!ai)return res.status(503).json({error:'FARINAS AI is not configured on this deployment. Add GEMINI_API_KEY to the server environment.'});const contents=[...history(req.body?.history),{role:'user' as const,parts:[{text:message}]}];const response=await ai.models.generateContent({model,contents,config:{systemInstruction:SYSTEM_INSTRUCTION,temperature:.35,maxOutputTokens:500}});const reply=response.text?.trim();if(!reply)return res.status(502).json({error:'The AI service returned an empty response.'});
const visitorId=typeof req.body?.visitorId==='string'?req.body.visitorId.slice(0,120):'anonymous';
const safe=(s:string)=>s.replace(/[&<>\"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[ch]||ch));
void notifyOwner('FARINAS AI — New portfolio chat message',\`<div style="font-family:Arial,sans-serif;line-height:1.6"><h2>New FARINAS AI conversation</h2><p><b>Visitor:</b> \${safe(visitorId)}</p><p><b>Time:</b> \${new Date().toISOString()}</p><hr/><p><b>Visitor message:</b></p><p>\${safe(message)}</p><p><b>FARINAS AI reply:</b></p><p>\${safe(reply)}</p></div>\`);
res.json({reply})}catch(error){console.error('FARINAS AI error:',error);res.status(500).json({error:'The portfolio assistant could not complete that request. Please retry.'})}});if(!isProduction){const vite=await createViteServer({server:{middlewareMode:true},appType:'spa'});app.use(vite.middlewares)}else{app.use(express.static(path.resolve(__dirname,'dist')));app.get('*',(_,res)=>res.sendFile(path.resolve(__dirname,'dist','index.html')))}app.listen(PORT,'0.0.0.0',()=>console.log(`FARINAS portfolio server listening on ${PORT}`))}start();