import React,{useCallback,useEffect,useRef,useState}from'react';
import{Bot,CheckCircle2,Minus,RotateCcw,Send,Sparkles,User,X}from'lucide-react';
type Msg={id:string;role:'user'|'model';text:string;time:string;error?:boolean};
type Props={isOpen:boolean;onClose:()=>void};
const prompts=['What projects has Farinas built?','What tools does she use?','Tell me about her AI work.','What is Vibe Coder?'];
const time=()=>new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});
export const ChatbotPanel:React.FC<Props>=({isOpen,onClose})=>{
 const[visitorId]=useState(()=>{try{const k='farinas-ai-visitor';const old=window.localStorage.getItem(k);if(old)return old;const uuid=typeof window.crypto?.randomUUID==='function'?window.crypto.randomUUID():Math.random().toString(36).slice(2)+Date.now().toString(36);const id='visitor-'+uuid;window.localStorage.setItem(k,id);return id}catch{return 'visitor-'+Date.now().toString(36)}});
 const[messages,setMessages]=useState<Msg[]>([{id:'welcome',role:'model',text:"Hi, I'm FARINAS AI. Ask me about Farinas Mumtaj H's projects, tools, AI work, UI/UX interests, ECE background, or Vibe Coder identity.",time:time()}]);
 const[input,setInput]=useState('');const[loading,setLoading]=useState(false);const[min,setMin]=useState(false);const[last,setLast]=useState<string|null>(null);
 const end=useRef<HTMLDivElement>(null);const inputRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{if(isOpen&&!min){end.current?.scrollIntoView({behavior:'smooth'});const t=setTimeout(()=>inputRef.current?.focus(),120);return()=>clearTimeout(t)}},[isOpen,min,messages,loading]);
 useEffect(()=>{if(!isOpen)return;const f=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose()};addEventListener('keydown',f);return()=>removeEventListener('keydown',f)},[isOpen,onClose]);
 const send=useCallback(async(value?:string)=>{
  const text=(value??input).trim();if(!text||loading)return;
  const user={id:'u-'+Date.now(),role:'user' as const,text,time:time()};const history=messages.filter(m=>!m.error).slice(-8).map(m=>({role:m.role,content:m.text}));
  setMessages(m=>[...m,user]);setInput('');setLoading(true);setLast(null);
  try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,history,visitorId})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed');setMessages(m=>[...m,{id:'a-'+Date.now(),role:'model',text:d.reply||'I do not have a verified answer for that yet.',time:time()}])}
  catch(e){console.error(e);setLast(text);setMessages(m=>[...m,{id:'e-'+Date.now(),role:'model',text:'FARINAS AI is temporarily unavailable. Please retry, or use the contact section for direct communication.',time:time(),error:true}])}
  finally{setLoading(false)}
 },[input,loading,messages]);
 if(!isOpen)return null;
 return <div className={`fixed z-[80] right-4 sm:right-6 bottom-4 sm:bottom-6 ${min?'w-[300px] h-14':'w-[calc(100vw-2rem)] sm:w-[430px] max-w-[calc(100vw-2rem)] h-[min(640px,calc(100vh-2rem))]'}`} role="dialog" aria-modal="false" aria-labelledby="farinas-ai-title">
  <div className="relative h-full overflow-hidden rounded-[24px] border border-white/15 bg-[#0b0d12]/95 text-white shadow-[0_28px_90px_rgba(0,0,0,.45)] backdrop-blur-2xl [transform:perspective(1200px)_rotateX(1deg)]">
   <div className="pointer-events-none absolute -inset-20 bg-[radial-gradient(circle_at_top_right,rgba(37,99,235,.20),transparent_42%),radial-gradient(circle_at_bottom_left,rgba(234,88,12,.10),transparent_36%)]"/>
   <header className="relative flex items-center justify-between border-b border-white/10 px-4 py-3.5">
    <div className="flex items-center gap-3"><div className="relative grid h-9 w-9 place-items-center rounded-xl border border-blue-400/30 bg-blue-500/15"><Bot className="h-4 w-4 text-blue-300"/><span className="absolute -right-0.5 -top-0.5 h-2.5 w-2.5 rounded-full border-2 border-[#0b0d12] bg-emerald-400"/></div><div><div className="flex items-center gap-2"><h2 id="farinas-ai-title" className="font-heading text-sm font-bold">FARINAS AI</h2><span className="font-mono-numbers text-[9px] tracking-widest text-blue-300">LIVE</span></div><p className="font-mono-numbers text-[9px] text-white/45">Portfolio intelligence · verified context</p></div></div>
    <div className="flex gap-1"><button type="button" onClick={()=>setMin(v=>!v)} aria-label={min?'Expand chatbot':'Minimize chatbot'} className="rounded-lg p-2 text-white/50 hover:bg-white/10 hover:text-white"><Minus className="h-4 w-4"/></button><button type="button" onClick={onClose} aria-label="Close chatbot" className="rounded-lg p-2 text-white/50 hover:bg-red-500/10 hover:text-red-300"><X className="h-4 w-4"/></button></div>
   </header>
   {!min&&<><div className="relative flex-1 overflow-y-auto px-4 py-4" style={{height:'calc(100% - 126px)'}}>
    <div className="mb-4 flex gap-2 rounded-xl border border-blue-400/15 bg-blue-400/5 p-3 text-[10px] leading-relaxed text-white/55"><Sparkles className="mt-0.5 h-3.5 w-3.5 shrink-0 text-blue-300"/><span>Grounded in the portfolio. Messages may be emailed to Farinas for portfolio follow-up. If a fact is not provided, FARINAS AI will say so instead of inventing it.</span></div>
    <div className="space-y-3">{messages.map(m=>{const u=m.role==='user';return <div key={m.id} className={`flex gap-2 ${u?'justify-end':'justify-start'}`}>{!u&&<div className="mt-1 grid h-6 w-6 shrink-0 place-items-center rounded-lg border border-blue-400/20 bg-blue-400/10"><Sparkles className="h-3 w-3 text-blue-300"/></div>}<div className={`max-w-[84%] rounded-2xl border px-3.5 py-2.5 text-[12px] leading-relaxed ${u?'border-blue-400/30 bg-blue-600':'border-white/10 bg-white/[.045] text-white/80'}`}><p className="whitespace-pre-wrap">{m.text}</p><div className="mt-1 flex items-center justify-end gap-1 font-mono-numbers text-[8px] text-white/35">{m.time}{u&&<CheckCircle2 className="h-2.5 w-2.5"/>}</div>{m.error&&last&&<button type="button" onClick={()=>send(last)} className="mt-2 inline-flex items-center gap-1 rounded-lg border border-red-300/20 bg-red-400/10 px-2 py-1 text-[10px]"><RotateCcw className="h-3 w-3"/>Retry</button>}</div>{u&&<div className="mt-1 grid h-6 w-6 shrink-0 place-items-center rounded-lg border border-white/10 bg-white/5"><User className="h-3 w-3 text-white/50"/></div>}</div>})}{loading&&<div className="flex items-center gap-2"><div className="grid h-6 w-6 place-items-center rounded-lg bg-blue-400/10"><Bot className="h-3 w-3 text-blue-300"/></div><div className="rounded-2xl border border-white/10 bg-white/[.045] px-3 py-2 text-[10px] text-white/45">Thinking…</div></div>}<div ref={end}/></div>
   </div><div className="relative border-t border-white/10 bg-[#090b10]/80 px-3 py-2"><div className="flex gap-1.5 overflow-x-auto pb-1">{prompts.map(p=><button key={p} type="button" onClick={()=>send(p)} disabled={loading} className="shrink-0 rounded-full border border-white/10 bg-white/[.04] px-2.5 py-1 text-[9px] text-white/55 hover:border-blue-400/30 hover:text-white disabled:opacity-40">{p}</button>)}</div></div><form onSubmit={e=>{e.preventDefault();void send()}} className="relative flex gap-2 border-t border-white/10 bg-[#080a0e] p-3"><input ref={inputRef} value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask about Farinas…" aria-label="Message FARINAS AI" disabled={loading} className="min-w-0 flex-1 rounded-xl border border-white/10 bg-white/[.045] px-3.5 py-2.5 text-xs text-white outline-none placeholder:text-white/30 focus:border-blue-400/50"/><button type="submit" disabled={loading||!input.trim()} aria-label="Send message" className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-blue-600 disabled:opacity-35"><Send className="h-4 w-4"/></button></form></>}
   {min&&<button type="button" onClick={()=>setMin(false)} className="flex h-[calc(100%-56px)] w-full items-center justify-between px-4 text-xs text-white/65"><span>FARINAS AI is active</span><Sparkles className="h-4 w-4 text-blue-300"/></button>}
  </div></div>
}