import React,{useEffect,useMemo,useState}from'react';
import{ArrowDown,ArrowUpRight,BrainCircuit,Camera,ChevronRight,Code2,ExternalLink,Layers3,Mail,Menu,MessageCircle,MousePointer2,Sparkles,X,Zap}from'lucide-react';
import{ChatbotPanel}from'./components/ChatbotPanel';

const PHOTO='/assets/farinas-profile.jpg';
const projects=[
 ['01','OBSTACLE AVOIDANCE ROBOT','HARDWARE / PROTOTYPE','Arduino-based robot using an ultrasonic sensor to detect obstacles and control movement to avoid collisions.','Arduino • Ultrasonic Sensor • Motor Driver • Motors'],
 ['02','FINANCE CHATBOT','AI / CONVERSATIONAL UI','AI-powered conversational finance project exploring interaction with financial information through a chat interface.','AI • Prompt Engineering • Conversational UI'],
 ['03','AI RESEARCH AGENT','AI / WORKFLOW','AI-assisted research project exploring how AI can organize research tasks, process information and structure findings.','AI Agents • Prompt Engineering • Research Workflow'],
 ['04','SMART ATTENDANCE','WEB / QR','QR-based attendance concept with a digital dashboard for organizing attendance information.','React • TypeScript • Tailwind CSS • Local Storage • QR'],
 ['05','ECOCART','UI/UX / CONCEPT','Digital shopping concept exploring a more sustainable and user-friendly shopping experience.','UI/UX • Product Design • Sustainability'],
 ['06','CAMPUSCONNECT','UI/UX / CONCEPT','Student-focused digital platform concept for useful campus information and services.','UI/UX • Information Architecture • Student Experience'],
 ['07','BANKWISE','UI/UX / FINTECH','Digital finance and banking interface concept focused on presenting financial information simply.','UI/UX • Information Design • FinTech'],
 ['08','AI INNOVATE SYMPOSIUM','WEB / AI-ASSISTED','AI-assisted web design project created using Google AI Studio and prompt engineering workflows.','Google AI Studio • HTML • CSS • JavaScript'],
 ['09','TRUEWEATHER','WEB / EXPERIMENT','Weather-focused web project created through AI-assisted development and interface experimentation.','AI-assisted development • Web UI']
] as const;

function useScrollSpy(){const[id,setId]=useState('home');useEffect(()=>{const els=[...document.querySelectorAll('main section[id]')];const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)setId(e.target.id)}),{rootMargin:'-25% 0px -60%'});els.forEach(e=>io.observe(e));return()=>io.disconnect()},[]);return id}
function FlipIdentityCard({onChat}:{onChat:()=>void}){const[flipped,setFlipped]=useState(false);const[tilt,setTilt]=useState({x:0,y:0});const toggle=()=>setFlipped(v=>!v);return <div className="identity-wrap"><div className={`identity-card ${flipped?'is-flipped':''}`} style={{'--rx':`${tilt.y}deg`,'--ry':`${tilt.x}deg`} as React.CSSProperties} onPointerMove={e=>{if(e.pointerType!=='mouse')return;const r=e.currentTarget.getBoundingClientRect();setTilt({x:(e.clientX-r.left-r.width/2)/28,y:-(e.clientY-r.top-r.height/2)/28})}} onPointerLeave={()=>setTilt({x:0,y:0})}><button className="card-hit" onClick={toggle} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle()}}} aria-label={flipped?'Show Farinas photo':'Flip Farinas identity card'}><span className="face front"><img src={PHOTO} alt="Farinas Mumtaj H" /><span className="photo-shade"/><span className="card-index">FMH / 01</span><span className="card-hint"><Sparkles/> FLIP IDENTITY</span></span><span className="face back"><span className="back-orbit one"/><span className="back-orbit two"/><span className="back-kicker">AI CREATIVE DESIGNER</span><strong>FARINAS<br/>MUMTAJ H</strong><span className="back-rule"/><span>ECE • AI • UI/UX<br/>CREATIVE TECHNOLOGY</span><b>VIBE CODER</b><small>PROMPT ENGINEERING</small></span></button></div><button className="card-chat" onClick={onChat}><MessageCircle/> Ask FARINAS AI</button></div>}

function ProjectCard({p,onOpen}:{p:typeof projects[number],onOpen:(p:typeof projects[number])=>void}){return <button className="project-card" onClick={()=>onOpen(p)}><span className="project-no">{p[0]}</span><span className="project-cube"><span/><span/><span/></span><span className="project-body"><em>{p[2]}</em><strong>{p[1]}</strong><p>{p[3]}</p><small>{p[4]}</small></span><ArrowUpRight className="project-arrow"/></button>}

export default function App(){const active=useScrollSpy();const[chat,setChat]=useState(false);const[menu,setMenu]=useState(false);const[selected,setSelected]=useState<typeof projects[number]|null>(null);const nav=useMemo(()=>[['home','01'],['about','02'],['projects','03'],['contact','04']],[]);useEffect(()=>{document.body.classList.toggle('modal-open',!!selected||chat);return()=>document.body.classList.remove('modal-open')},[selected,chat]);return <><header className="topbar"><a className="brand" href="#home"><span className="brand-mark">FM</span><span>FARINAS MUMTAJ H</span></a><button className="menu-btn" onClick={()=>setMenu(v=>!v)} aria-label="Toggle navigation"><Menu/></button><nav className={menu?'open':''}>{nav.map(([id,n])=><a key={id} className={active===id?'active':''} href={`#${id}`} onClick={()=>setMenu(false)}><span>{n}</span>{id.toUpperCase()}</a>)}<button className="nav-chat" onClick={()=>{setChat(true);setMenu(false)}}><MessageCircle/> CHAT</button></nav></header>
<main>
<section id="home" className="hero section"><div className="hero-grid"/><div className="hero-copy"><div className="eyebrow"><span className="pulse"/> AI CREATIVE DESIGNER <i>•</i> ECE</div><h1>Ideas into<br/><span>experiences.</span></h1><p className="hero-lead">I combine AI, code, interface design and creative experimentation to turn rough ideas into tangible digital experiences.</p><div className="hero-actions"><a className="primary" href="#projects">Explore work <ArrowUpRight/></a><button className="secondary" onClick={()=>setChat(true)}>Talk to FARINAS AI <Sparkles/></button></div><div className="hero-meta"><span><b>09</b> selected projects</span><span><b>AI</b> + UI/UX + ECE</span><span><b>01</b> creative system</span></div></div><div className="hero-card"><FlipIdentityCard onChat={()=>setChat(true)}/></div><a className="scroll-cue" href="#about"><MousePointer2/> SCROLL TO EXPLORE <ArrowDown/></a></section>

<section id="about" className="section about"><div className="section-label"><span>02</span> ABOUT / SYSTEM</div><div className="about-grid"><div><h2>Design is where<br/><span>technology feels human.</span></h2></div><div className="about-copy"><p>Farinas Mumtaj H is an ECE student exploring the intersection of artificial intelligence, UI/UX, prompt engineering and creative technology.</p><p>Her workflow moves between visual design, AI-assisted development, no-code experiments, code and physical electronics—learning by building.</p><div className="signal-list"><div><Zap/> <span><b>AI + PROMPT ENGINEERING</b><small>Exploring AI tools, workflows and prompt-created experiences.</small></span></div><div><Layers3/><span><b>UI/UX + CREATIVE TECH</b><small>Wireframing, interfaces, visual systems and digital product thinking.</small></span></div><div><Code2/><span><b>ECE + BUILDING</b><small>C, electronics projects and hands-on experimentation.</small></span></div></div></div></div></section>

<section id="projects" className="section projects"><div className="section-head"><div><div className="section-label"><span>03</span> SELECTED WORK</div><h2>Built, explored,<br/><span>experimented.</span></h2></div><p>Click a card to inspect the project. Each description stays within the verified scope of the portfolio.</p></div><div className="project-grid">{projects.map(p=><ProjectCard key={p[0]} p={p} onOpen={setSelected}/>)}</div></section>

<section id="contact" className="section contact"><div className="contact-orb"><div><BrainCircuit/></div></div><div><div className="section-label"><span>04</span> LET'S CONNECT</div><h2>Have an idea?<br/><span>Let's make it real.</span></h2><p>Use FARINAS AI to explore the portfolio, ask about projects and tools, or reach out directly.</p><div className="contact-actions"><button className="primary" onClick={()=>setChat(true)}>Open FARINAS AI <Sparkles/></button><a className="secondary" href="mailto:farinasmumtaj6399@gmail.com">Email Farinas <Mail/></a></div></div></section>
</main>
<footer><span>© {new Date().getFullYear()} FARINAS MUMTAJ H</span><span>AI • UI/UX • ECE • CREATIVE TECHNOLOGY</span><a href="#home"><ArrowUp/></a></footer>

{selected&&<div className="modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><article className="project-modal" role="dialog" aria-modal="true" aria-label={selected[1]}><button className="modal-close" onClick={()=>setSelected(null)} aria-label="Close"><X/></button><div className="modal-art"><span>{selected[0]}</span><div className="art-lines"/><div className="art-core"><Sparkles/></div></div><div className="modal-copy"><span className="modal-kicker">{selected[2]}</span><h3>{selected[1]}</h3><p>{selected[3]}</p><div className="modal-tools">{selected[4].split(' • ').map(x=><span key={x}>{x}</span>)}</div><div className="modal-status">PROJECT STATUS <b>PORTFOLIO PROJECT / VERIFIED SCOPE</b></div></div></article></div>}
<ChatbotPanel isOpen={chat} onClose={()=>setChat(false)}/></>}
